# Generated by Django 5.1.1 on 2024-10-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='number',
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback',
            field=models.TextField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
